### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by r2k1** [tomarrell/wrapcheck#16] opened 2021-07-27 03:19 UTC
I'd like to use the new `ignorePackageGlobs` feature 

https://github.com/tomarrell/wrapcheck/commit/d409df3395169cccdb7f39aea3092e20c5e69a9c

But it wasn't released yet.

Do you plan to release it?

**Comment by tomarrell** [comment] 2021-07-27 09:30
Yeah sure, I was hoping for some more feedback, but if you're happy with it the way it is I can make a new release ASAP.

**Comment by r2k1** [comment] 2021-07-28 21:13
We use attach stack-traces to errors in my project.
So wrapping errors created inside the project isn't really necessary (and in some cases annoying).

So I'd like to add my project to `ignorePackageGlobs`.

I tested the latest version on my relatively small project and the most false positives are gone. (marked with `// nolint: wrapcheck`)

The only issue I found is #17. It is also present in v2.2.0, so it doesn't look like a recent regression.

It's not available in `golangci-lint`, so it doesn't really fit in our workflow and is a bit tricky to trial.

**Comment by tomarrell** [comment] 2021-07-29 16:16
Sounds good. Thanks for giving it a shot.

As the issue isn't a regression, I'll cut a release. Thanks for reporting the issue as well.

**Comment by tomarrell** [comment] 2021-07-29 16:26
Closing with release https://github.com/tomarrell/wrapcheck/releases/tag/v2.3.0

I will update wrapcheck in golangci-lint so that it gets released with the next version over there.

**Closed by tomarrell** 2021-07-29 16:26 UTC

**Comment by tomarrell** [comment] 2021-08-03 09:00
@r2k1 the new version should be available in the next release of golangci-lint, version `1.42.0`.
